baseURL = "https://detailingarsenal.com/"
languageCode = "en-us"
title = "Detailing Arsenal"
theme = "blank"

[menu]
    [[menu.main]]
    identifier = "pricing"
    name = "Pricing"
    url = "/pricing"
    weight = 1

    [[menu.main]]
    identifier = "about-us"
    name = "About Us"
    url = "/about-us"
    weight = 2

    [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 3
