baseURL = "https://detailingarsenal.com/"
languageCode = "en-us"
title = "Detailing Arsenal"
theme = "blank"

[menu]
    [[menu.main]]
    identifier = "about-us"
    name = "About Us"
    url = "#about-us"
    weight = 1

    [[menu.main]]
    identifier = "pricing"
    name = "Pricing"
    url = "#pricing"
    weight = 2

    [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "#contact"
    weight = 3

    [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 4