name: Build and Deploy ASP.NET Core API to Digital Ocean

on: 
  push:
    branches: [ master ]
    paths: 
    - 'api/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build with dotnet
      run: dotnet build ./api/Backend.sln --configuration Release
    - name: Run Tests
      run: dotnet test ./api/Backend.sln --filter TestCategory!=Integration
    - name: dotnet publish 
      run: |
        dotnet publish ./api/Backend.sln --configuration Release -o public
    - name: Push code to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        port: ${{ secrets.REMOTE_PORT }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "public"
        target: "/var/www/detailingarsenal-api"
    - name: Reload kestrel service running API project
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        port: ${{ secrets.REMOTE_PORT }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: systemctl restart detailingarsenal-api
          
          
          
          
          
          
          
          
          
          
          
